### ISSUE TITLE
The pull request url is invalid

### ISSUE THREAD

**Issue by palash25** [littlewonder/gitstalk#11]
When I see an activity like
`<username> created a <pull-request> on .....`

and click on the pr link it leads nowhere since the url path is wrong
The path that it goes to is 
`www.github.com/:org_name/:repo_name/pulls/:pr_no`

For individual PRs github uses the path `pull` and not `pulls` (which it currently uses)
So it should be something like
`www.github.com/:org_name/:repo_name/pull/:pr_no`

Cool app btw :+1:

**Comment by littlewonder** [comment]
Fixed. Thank you 😄
